name: Compile PDFs

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make
      
    - uses: actions/upload-artifact@v3
      with:
        name: en
        path: en/*.pdf

    - uses: actions/upload-artifact@v3
      with:
        name: it
        path: it/*.pdf
